export const vocabData = [
  {
    _id: 1,
    en: "a little bit",
    ua: "трохи, трішки",
    progress: 10,
    category: "participle",
    isIrregular: false,
  },
  {
    _id: 2,
    en: "break in",
    ua: "вмішуватися, встрявати",
    progress: 20,
    category: "verb",
    isIrregular: false,
  },
  {
    _id: 3,
    en: "care",
    ua: "турбота, догляд",
    progress: 30,
    category: "noun",
    isIrregular: false,
  },
  {
    _id: 4,
    en: "during",
    ua: "протягом, під час",
    progress: 40,
    category: "participle",
    isIrregular: false,
  },
  {
    _id: 5,
    en: "care",
    ua: "турбота, догляд",
    progress: 50,
    category: "noun",
    isIrregular: false,
  },
  {
    _id: 6,
    en: "during",
    ua: "протягом, під час",
    progress: 60,
    category: "participle",
    isIrregular: false,
  },
  {
    _id: 7,
    en: "a little bit",
    ua: "трохи, трішки",
    progress: 70,
    category: "participle",
    isIrregular: false,
  },
  {
    _id: 8,
    en: "break in",
    ua: "вмішуватися, встрявати",
    progress: 80,
    category: "verb",
    isIrregular: false,
  },
  {
    _id: 9,
    en: "care",
    ua: "турбота, догляд",
    progress: 90,
    category: "noun",
    isIrregular: false,
  },
  {
    _id: 10,
    en: "during",
    ua: "протягом, під час",
    progress: 100,
    category: "participle",
    isIrregular: false,
  },
  {
    _id: 11,
    en: "care",
    ua: "турбота, догляд",
    progress: 65,
    category: "noun",
    isIrregular: false,
  },
  {
    _id: 12,
    en: "During",
    ua: "Протягом, під час",
    progress: 75,
    category: "participle",
    isIrregular: false,
  },
  {
    _id: 13,
    en: "care",
    ua: "турбота, догляд",
    progress: 55,
    category: "noun",
    isIrregular: false,
  },
  {
    _id: 14,
    en: "during",
    ua: "протягом, під час",
    progress: 35,
    category: "participle",
    isIrregular: false,
  },
  {
    _id: 15,
    en: "a little bit",
    ua: "трохи, трішки",
    progress: 25,
    category: "participle",
    isIrregular: false,
  },
];